services:
  postgres:
    container_name: postgres-customer
    image: postgres:12.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: constantin
      POSTGRES_PASSWORD: constantin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  tracker-investor:
    container_name: tracker-investor
    image: postgres:12.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: constantin
      POSTGRES_PASSWORD: constantin
    volumes:
      - tracker-investor:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.13
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: Ileniaaurora13
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  tracker-investor:
